### ISSUE TITLE
pcm_is_ready(_pcm)

### ISSUE THREAD

**Issue by circinusX1** [Gateworks/tinyalsa#1]
The pcm_is_ready fails:

`
                QString dn="default";
                _pcm = ::pcm_open_by_name((const char*)dn.toUtf8(),flags,&_config);
                //_pcm = ::pcm_open(card, device, flags, &_config);
                pcm_is_ready(_pcm); /// fails

`
Any ideas.
Thank you.

**Comment by Gateworks** [comment]
Sorry, I'm not sure without more details such as what board you are using and what audio output you are trying to use. Please e-mail support@gateworks.com with these details so that our support team can assist you.

**Comment by circinusX1** [comment]
Hi,
I stepped into the code and open("/dev/pcmC#D#p") fails with errno 13, (access denied). Looks like you have to be root or have a rooted device.
